### PR TITLE
add arguments to wrapper script

### LINKED ISSUE #2: Cannot open transciption file (.xsc) file from file manager.
Opening a transcription file (.xsc) file from file manager (nautilus) only starts application because `transcribe-wrapper` does not pass the file path to the application, due to missing argument.

### PR DESCRIPTION
**Pull request by MichaHoffmann**
This PR fixes #2 by adding the missing arguments to the wrapper script.

### CODE REVIEW

**Comment by hfiguiere** [comment]
The .desktop file need also to have the proper parameter like `%f` 

https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html

**Comment by MichaHoffmann** [comment]
> The .desktop file need also to have the proper parameter like `%f`
> 
> https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html

Hey! thanks i did miss that! 

Edit: since the desktop file is built from the original just by replacing the binary name, i think its already there! Looking at it in my install it looks like: 

```mhoffm@fedora:~$ cat .local/share/flatpak/app/com.seventhstring.Transcribe/current/active/export/share/applications/com.seventhstring.Transcribe.desktop
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
MimeType=application/seventhstring-transcribe;
Exec=/usr/bin/flatpak run --branch=test --arch=x86_64 --command=/app/bin/transcribe-wrapper --file-forwarding com.seventhstring.Transcribe @@ %f @@
Categories=Audio;
Terminal=false
Icon=com.seventhstring.Transcribe
Name=Transcribe!
X-Flatpak-RenamedFrom=seventhstring-transcribe.desktop;
X-Flatpak=com.seventhstring.Transcribe
```

that should be sufficient, right?

**Comment by MichaHoffmann** [comment]
Question: Im not sure whats the process, can i merge this already or should someone other than the author merge the PR?

**Comment by hfiguiere** [comment]
You are the maitainer, it's your call.

> > The .desktop file need also to have the proper parameter like `%f`
> > https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html
> 
> Hey! thanks i did miss that!
> 
> that should be sufficient, right?

Here:
https://github.com/flathub/com.seventhstring.Transcribe/blob/master/com.seventhstring.Transcribe.yml#L47

you change it.

And that's what I meant. Maybe it doesn't matter.

BTW the prefered way to "edit" desktop files is to use `desktop-file-edit`

**Comment by MichaHoffmann** [comment]
> You are the maitainer, it's your call.
> 
> > > The .desktop file need also to have the proper parameter like `%f`
> > > https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html
> > 
> > 
> > Hey! thanks i did miss that!
> > that should be sufficient, right?
> 
> Here: https://github.com/flathub/com.seventhstring.Transcribe/blob/master/com.seventhstring.Transcribe.yml#L47
> 
> you change it.
> 
> And that's what I meant. Maybe it doesn't matter.
> 
> BTW the prefered way to "edit" desktop files is to use `desktop-file-edit`

I removed the line completely, since i learned that its already handled by the `rename-desktop-file` option!

**Comment by ptrv** [comment]
> > You are the maitainer, it's your call.
> > > > The .desktop file need also to have the proper parameter like `%f`
> > > > https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html
> > > 
> > > 
> > > Hey! thanks i did miss that!
> > > that should be sufficient, right?
> > 
> > 
> > Here: https://github.com/flathub/com.seventhstring.Transcribe/blob/master/com.seventhstring.Transcribe.yml#L47
> > you change it.
> > And that's what I meant. Maybe it doesn't matter.
> > BTW the prefered way to "edit" desktop files is to use `desktop-file-edit`
> 
> I removed the line completely, since i learned that its already handled by the `rename-desktop-file` option!

I've updated the package from flathub and now the wrapper script is not used anymore. This is the Exec line in the .desktop file at ` now:
```
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/tmp/bin/transcribe/transcribe --file-forwarding com.seventhstring.Transcribe @@ %f @@
```
This uses now $HOME folder for persistent storage of session data and is not accessible without overriding filesystem to use home instead of xdg-music

I think the `sed` command is still needed to override the Exec and use the wrapper.

**Comment by hfiguiere** [comment]
you can do that with desktop-file-edit too :-) but it's not big deal which way. Yes it's still necessary.

**Comment by ptrv** [comment]
> you can do that with desktop-file-edit too :-) but it's not big deal which way. Yes it's still necessay.

Yes right that's better, I just meant Exec still needs to be changed :)

**Comment by MichaHoffmann** [comment]
Oh, sorry i missed that, ill open a new PR tomorrow to fix it!

**Comment by MichaHoffmann** [comment]
Should be fixed by #4

**Comment by ptrv** [comment]
Works as expected now. Thanks!

**Pull request merged**
